# Configuration settings for main.py
# Notes:
    # - optional parameters: MEMBER_NAMES
    # - MEMBER_NAMES must be in a markdown-style bulleted list
    # - if IDs are missing from this file, main.py will try to find them automatically

# Path settings
BASE_DIRECTORY: C:\full\path\to\reorganize-with-trello
REORG_DIRECTORY: C:\full\path\to\testdirectory2

# Trello settings
API_KEY: your_key
OATH_TOKEN: your_token
BOARD_NAME: your_board_name
LIST_NAME: your_list_name
MEMBER_NAMES:
- your_username1
- your_username2
- etc
BOARD_ID:
LIST_ID:
MEMBER_IDS:
